'use strict';
window.addEventListener('DOMContentLoaded',()=>{
 const $=id=>document.getElementById(id);
 const shuffle=items=>{const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
 const targetOf=t=>t.targetWord;
 const arrangeTasks=tasks=>{const buckets=new Map();tasks.forEach(t=>{const k=targetOf(t);if(!buckets.has(k))buckets.set(k,[]);buckets.get(k).push(t);});buckets.forEach((v,k)=>buckets.set(k,shuffle(v)));const out=[];while(out.length<tasks.length){const last=targetOf(out.at(-1)||{}),c=[...buckets.entries()].filter(([k,v])=>v.length&&k!==last);if(!c.length)break;const max=Math.max(...c.map(([,v])=>v.length));const [,bucket]=shuffle(c.filter(([,v])=>v.length===max))[0];out.push(bucket.pop());}return out;};
 const createDoubleExposureTasks=(items,pool,make)=>{const tasks=[];[...new Set(items)].forEach(target=>{const others=shuffle([...new Set(pool)].filter(x=>x!==target));if(!others.length)return;const ds=others.slice(0,2);if(ds.length===1)ds.push(ds[0]);ds.forEach(d=>tasks.push(make(target,d));});return arrangeTasks(tasks);};
 const availableWords=()=>wordsThroughLevel().filter(wordAvailable);
 const pool=()=>[...new Set(availableWords().map(x=>x.word))];
 const data=w=>availableWords().find(x=>x.word===w);
 const size=()=>Math.min(pool().length,5);
 const speakWord=w=>{if(!w||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(w);u.lang='en-GB';u.rate=.72;speechSynthesis.speak(u);};
 const shown=s=>typeof textCase==='function'?textCase(String(s)):String(s);
 const learning=(el,s)=>{el.textContent=shown(s);el.classList.toggle('cursive',String(mode||'').startsWith('cursive'));return el;};
 const completionHtml='<div class="game-fireworks">✨ 🎆 ✨ 🎉 ⭐</div><div class="game-dino">🦕</div><h1>Hooray!</h1><p>All tasks are complete!</p><button class="primary game-again">Play again</button>';
 const empty=(host,min)=>{host.innerHTML='<div class="game-header"><button class="game-back">← Games</button></div><div class="game-empty"><div class="game-dino">🦕</div><h2>More words needed</h2><p>Learn a few more sounds to unlock this game.</p><small>This game needs at least '+min+' decodable word'+(min===1?'':'s')+'.</small></div>';host.querySelector('.game-back').onclick=showList;};
 const style=document.createElement('style');style.textContent=`
 #gamesView{min-height:0;flex:1;width:100%;max-width:1120px;margin:0 auto;overflow:auto;padding:12px 0 24px;color:#123f73}
 .games-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:22px;width:min(100%,760px);margin:28px auto}.game-card{min-height:150px;background:#f8fbff;color:#123f73;border:1px solid #cbd9ea;border-radius:22px;box-shadow:0 4px 12px #123f7315;font-size:22px;display:grid;place-items:center;gap:6px}.game-card span{font-size:48px}.game-card:active{background:#2389e8;color:#fff;transform:scale(.985)}
 .en-game{width:min(100%,920px);margin:0 auto;text-align:center;position:relative}.game-header{display:flex;align-items:center;justify-content:center;position:relative;min-height:58px}.game-back{position:absolute;left:0;background:#f8fbff;color:#123f73;border:1px solid #cbd9ea}.game-title{font-size:25px;font-weight:850}.game-progress{display:flex;justify-content:center;gap:7px;margin:16px auto 24px}.game-step{width:25px;height:25px;border-radius:50%;background:#edf4fb;border:1px solid #cbd9ea;font-size:15px;display:grid;place-items:center}.game-step.done{background:#35b96f;color:white;border-color:#35b96f}.game-task{min-height:330px;display:grid;align-content:center;justify-items:center;gap:24px;position:relative;padding:0 76px}.game-picture{background:transparent;font-size:64px;min-height:70px;padding:0}.game-prompt{font-size:25px;font-weight:800}.game-answers{display:flex;flex-wrap:wrap;justify-content:center;gap:14px}.game-answer,.build-tile,.build-slot{min-width:92px;min-height:70px;padding:10px 18px;background:#f8fbff;color:#123f73;border:1px solid #cbd9ea;box-shadow:0 4px 12px #123f7315;border-radius:16px;font-size:34px;font-weight:800}.game-answer.correct,.build-slot.correct{background:#35b96f;color:white;border-color:#35b96f}.game-answer.wrong{box-shadow:0 0 0 3px #d6e0eb inset}.game-nav{position:absolute;top:50%;transform:translateY(-50%);width:58px;height:58px;min-height:58px;padding:0;border-radius:50%;background:white;color:#123f73;border:1px solid #cbd9ea}.game-prev{left:5px}.game-next{right:5px}.game-next.ready{background:#35b96f;color:#fff;border-color:#35b96f}.game-complete,.game-empty{min-height:430px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:12px}.game-complete h1,.game-complete p,.game-empty h2,.game-empty p{margin:0}.game-dino{font-size:74px}.game-fireworks{font-size:34px}.game-again{margin-top:22px}.build-slots,.build-tiles{display:flex;flex-wrap:wrap;justify-content:center;gap:10px}.build-slot{min-width:66px}.build-slot.empty{background:transparent;box-shadow:none;border:0;border-bottom:4px solid #cbd9ea;border-radius:0}.build-tile{min-width:66px}.build-tile:disabled{visibility:hidden}.missing-pair{display:grid;grid-template-columns:1fr 1fr;gap:20px;width:min(100%,520px)}.missing-word{min-height:86px;padding:15px;border-radius:16px;background:#f8fbff;border:1px solid #cbd9ea;font-size:38px;font-weight:800;display:grid;place-items:center}.catch-area{position:relative;width:100%;height:330px;overflow:hidden}.catch-answer{position:absolute;min-width:130px;min-height:78px;transition:transform 5s ease-in-out}.catch-answer.correct{background:#35b96f;color:white}.game-empty small{color:#7d8599}
 @media(max-width:700px){#childView .tabs{width:min(78%,360px)}.games-grid{gap:12px;margin-top:12px}.game-card{min-height:112px;font-size:17px}.game-card span{font-size:38px}.game-task{padding:0 54px;min-height:290px}.game-answer,.build-tile,.build-slot{font-size:27px;min-width:68px;min-height:60px}.game-nav{width:48px;height:48px;min-height:48px}.game-back{font-size:14px;padding:8px 10px}.missing-word{font-size:30px}}
 `;document.head.appendChild(style);
 const gamesTab=$('gamesTab'),view=$('gamesView'),grid=$('gamesGrid'),host=$('gameHost');if(!gamesTab||!view||!grid||!host)return;let active=null;
 const hidePractice=()=>{['practice','finish'].forEach(id=>{const e=$(id);if(e)e.hidden=true;});};
 function showList(){active=null;hidePractice();view.hidden=false;grid.hidden=false;host.hidden=true;gamesTab.classList.add('on');$('soundsTab')?.classList.remove('on');$('wordsTab')?.classList.remove('on');}
 const leaveGames=()=>{view.hidden=true;gamesTab.classList.remove('on');active=null;};
 $('soundsTab')?.addEventListener('click',leaveGames);$('wordsTab')?.addEventListener('click',leaveGames);gamesTab.onclick=showList;
 const progressHtml=(tasks)=>'<div class="game-progress">'+tasks.map(t=>'<span class="game-step'+(t.rewarded?' done':'')+'">'+(t.rewarded?'✓':'')+'</span>').join('')+'</div>';
 const finish=(restart)=>{host.innerHTML='<div class="game-complete">'+completionHtml+'</div>';host.querySelector('.game-again').onclick=restart;};
 const taskEngine=(tasks,render,restart)=>{let original=tasks,session=[...tasks],i=0;const current=()=>session[i],done=()=>original.length&&original.every(t=>t.rewarded);const nav=()=>{const prev=host.querySelector('.game-prev'),next=host.querySelector('.game-next');if(prev)prev.disabled=i===0;if(next){next.disabled=!current()?.completed;next.classList.toggle('ready',!!current()?.completed);}};const redraw=()=>{render(current(),{original,session,index:i,current,redraw,nav,next,prev,reward});nav();};const reward=(t,correct)=>{t.attempted=true;if(!correct){t.hadWrongAttempt=true;return false;}t.completed=true;if(!t.hadWrongAttempt&&!t.rewarded)t.rewarded=true;return t.rewarded;};const retry=()=>{session=shuffle(original.filter(t=>!t.rewarded).map(t=>({...t,attempted:false,completed:false,hadWrongAttempt:false})));i=0;redraw();};function next(){if(!current()?.completed)return;if(i<session.length-1){i++;redraw();}else if(done())finish(restart);else retry();}function prev(){if(i>0){i--;redraw();}}redraw();};
 const shell=(title,body,steps)=>{host.hidden=false;grid.hidden=true;host.innerHTML='<div class="en-game"><div class="game-header"><button class="game-back">← Games</button><span class="game-title">'+title+'</span></div>'+progressHtml(steps)+'<div class="game-task"><button class="game-nav game-prev">‹</button>'+body+'<button class="game-nav game-next">›</button></div></div>';host.querySelector('.game-back').onclick=showList;};
 function startFind(){active='find';const p=pool();if(p.length<2){host.hidden=false;grid.hidden=true;empty(host,2);return;}const words=shuffle(p).slice(0,size()),tasks=createDoubleExposureTasks(words,p,(targetWord,distractor)=>({targetWord,answers:shuffle([targetWord,distractor]),attempted:false,completed:false,hadWrongAttempt:false,rewarded:false}));taskEngine(tasks,(t,e)=>{shell('Find','<button class="game-picture">'+(data(t.targetWord)?.picture||'🔊')+'</button><div class="game-prompt">Find “'+shown(t.targetWord)+'”</div><div class="game-answers"></div>',e.original);const ans=host.querySelector('.game-answers');t.answers.forEach(label=>{const b=document.createElement('button');b.className='game-answer'+(t.completed&&label===t.targetWord?' correct':'');learning(b,label);b.onclick=()=>{if(t.completed)return;const ok=label===t.targetWord;e.reward(t,ok);if(ok){b.classList.add('correct');e.redraw();}else b.classList.add('wrong');};ans.append(b);});host.querySelector('.game-picture').onclick=()=>speakWord(t.targetWord);host.querySelector('.game-prev').onclick=e.prev;host.querySelector('.game-next').onclick=e.next;},startFind);}
 function startCatch(){active='catch';const p=pool();if(p.length<2){host.hidden=false;grid.hidden=true;empty(host,2);return;}const words=shuffle(p).slice(0,size()),tasks=createDoubleExposureTasks(words,p,(targetWord,distractor)=>({targetWord,answers:shuffle([targetWord,distractor]),attempted:false,completed:false,hadWrongAttempt:false,rewarded:false}));taskEngine(tasks,(t,e)=>{shell('Catch','<button class="game-picture">'+(data(t.targetWord)?.picture||'🔊')+'</button><div class="catch-area"></div>',e.original);const area=host.querySelector('.catch-area');t.answers.forEach((label,j)=>{const b=document.createElement('button');b.className='game-answer catch-answer'+(t.completed&&label===t.targetWord?' correct':'');learning(b,label);b.style.transform='translate('+(j?65:5)+'%, '+(j?180:20)+'px)';b.onclick=()=>{if(t.completed)return;const ok=label===t.targetWord;e.reward(t,ok);if(ok){b.classList.add('correct');e.redraw();}else b.classList.add('wrong');};area.append(b);});if(!t.completed)setTimeout(()=>{[...area.children].forEach((b,j)=>b.style.transform='translate('+(j?5:65)+'%, '+(j?20:180)+'px)');},30);host.querySelector('.game-picture').onclick=()=>speakWord(t.targetWord);host.querySelector('.game-prev').onclick=e.prev;host.querySelector('.game-next').onclick=e.next;},startCatch);}
 const shuffledGraphemes=(gs,avoid='')=>{for(let n=0;n<12;n++){const x=shuffle(gs);if(x.join('|')!==avoid&&x.join('|')!==gs.join('|'))return x;}return [...gs].reverse();};
 function startBuild(){active='build';const p=pool();if(p.length<1){host.hidden=false;grid.hidden=true;empty(host,1);return;}const words=shuffle(p).slice(0,size()),tasks=[];words.forEach(targetWord=>{const gs=graphemes(targetWord),a=shuffledGraphemes(gs),b=shuffledGraphemes(gs,a.join('|'));[a,b].forEach(order=>tasks.push({targetWord,graphemes:gs,tiles:order.map((g,id)=>({id,g})),placed:Array(order.length).fill(null),attempted:false,completed:false,hadWrongAttempt:false,rewarded:false}));});const arranged=arrangeTasks(tasks);taskEngine(arranged,(t,e)=>{shell('Build Word','<button class="game-picture">'+(data(t.targetWord)?.picture||'🔊')+'</button><div class="build-slots"></div><div class="build-tiles"></div>',e.original);const slots=host.querySelector('.build-slots'),tiles=host.querySelector('.build-tiles');t.placed.forEach(tile=>{const b=document.createElement('button');b.className='build-slot'+(!tile?' empty':'')+(t.completed?' correct':'');if(tile)learning(b,tile.g);b.disabled=!tile||t.completed;if(tile)b.onclick=()=>{const k=t.placed.findIndex(x=>x?.id===tile.id);if(k>=0)t.placed[k]=null;e.redraw();};slots.append(b);});t.tiles.forEach(tile=>{const b=document.createElement('button');b.className='build-tile';learning(b,tile.g);b.disabled=t.completed||t.placed.some(x=>x?.id===tile.id);b.onclick=()=>{const k=t.placed.findIndex(x=>x===null);if(k<0)return;t.placed[k]=tile;if(t.placed.every(Boolean)){const assembled=t.placed.map(x=>x.g).join('');const expected=t.graphemes.join('');const ok=assembled===expected;e.reward(t,ok);if(!ok)setTimeout(()=>{t.placed=Array(t.tiles.length).fill(null);e.redraw();},350);else e.redraw();}else e.redraw();};tiles.append(b);});host.querySelector('.game-picture').onclick=()=>speakWord(t.targetWord);host.querySelector('.game-prev').onclick=e.prev;host.querySelector('.game-next').onclick=e.next;},startBuild);}
 function startMissing(){active='missing';const p=pool();if(p.length<2){host.hidden=false;grid.hidden=true;empty(host,2);return;}const words=shuffle(p).slice(0,size()),tasks=[];words.forEach(targetWord=>{for(let n=0;n<2;n++){const other=shuffle(words.filter(w=>w!==targetWord))[0]||shuffle(p.filter(w=>w!==targetWord))[0];if(!other)continue;const distractor=shuffle(p.filter(w=>w!==targetWord&&w!==other))[0]||other;const first=Math.random()<.5?targetWord:other,second=first===targetWord?other:targetWord;tasks.push({targetWord,first,second,missing:targetWord,answers:shuffle([...new Set([targetWord,distractor])]),phase:'memorize',attempted:false,completed:false,hadWrongAttempt:false,rewarded:false});}});const arranged=arrangeTasks(tasks);let timer=0;const restart=()=>{clearTimeout(timer);startMissing();};taskEngine(arranged,(t,e)=>{clearTimeout(timer);const answer=t.phase==='answer';shell("What’s Missing?",'<div class="game-prompt">'+(answer?'What’s missing?':'Remember')+'</div><div class="missing-pair"><div class="missing-word" id="mw1"></div><div class="missing-word" id="mw2"></div></div><div class="game-answers"></div>',e.original);const one=host.querySelector('#mw1'),two=host.querySelector('#mw2');if(answer&&!t.completed&&t.first===t.missing)one.textContent='?';else learning(one,t.first);if(answer&&!t.completed&&t.second===t.missing)two.textContent='?';else learning(two,t.second);if(answer){const box=host.querySelector('.game-answers');t.answers.forEach(label=>{const b=document.createElement('button');b.className='game-answer'+(t.completed&&label===t.missing?' correct':'');learning(b,label);b.onclick=()=>{if(t.completed)return;const ok=label===t.missing;e.reward(t,ok);if(ok)e.redraw();else b.classList.add('wrong');};box.append(b);});}else{const sec=Number(localStorage.getItem('phonika-en-missing-memory-seconds')||10);timer=setTimeout(()=>{t.phase='answer';e.redraw();},[5,7,10,15].includes(sec)?sec*1000:10000);}host.querySelector('.game-prev').onclick=e.prev;host.querySelector('.game-next').onclick=e.next;},restart);}
 grid.querySelector('[data-game="find"]').onclick=startFind;grid.querySelector('[data-game="catch"]').onclick=startCatch;grid.querySelector('[data-game="build"]').onclick=startBuild;grid.querySelector('[data-game="missing"]').onclick=startMissing;
 $('parentOpen')?.addEventListener('click',()=>{if(!view.hidden)localStorage.setItem('phonika-en-return-games',active||'list');});
 $('parentBack')?.addEventListener('click',()=>{const ret=localStorage.getItem('phonika-en-return-games');if(!ret)return;localStorage.removeItem('phonika-en-return-games');requestAnimationFrame(()=>{showList();if(ret==='find')startFind();else if(ret==='catch')startCatch();else if(ret==='build')startBuild();else if(ret==='missing')startMissing();});});
 window.PhonikaGamesEN={shuffle,arrangeTasks,availableWords,pool,graphemesForWord:graphemes};
});
