'use strict';
function initGames(){
 const $=id=>document.getElementById(id);
 const shuffle=items=>{const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
 const targetOf=t=>t.targetWord;
 const arrangeTasks=tasks=>{const buckets=new Map();tasks.forEach(t=>{const k=targetOf(t);if(!buckets.has(k))buckets.set(k,[]);buckets.get(k).push(t);});buckets.forEach((v,k)=>buckets.set(k,shuffle(v)));const out=[];while(out.length<tasks.length){const last=targetOf(out.at(-1)||{}),c=[...buckets.entries()].filter(([k,v])=>v.length&&k!==last);if(!c.length)break;const max=Math.max(...c.map(([,v])=>v.length));const [,bucket]=shuffle(c.filter(([,v])=>v.length===max))[0];out.push(bucket.pop());}return out;};
 const createDoubleExposureTasks=(items,pool,make)=>{const tasks=[];[...new Set(items)].forEach(target=>{const others=shuffle([...new Set(pool)].filter(x=>x!==target));if(!others.length)return;const ds=others.slice(0,2);if(ds.length===1)ds.push(ds[0]);ds.forEach(d=>tasks.push(make(target,d)));});return arrangeTasks(tasks);};
 const availableWords=()=>wordsThroughLevel().filter(wordAvailable);
 const pool=()=>[...new Set(availableWords().map(x=>x.word))];
 const data=w=>availableWords().find(x=>x.word===w);
 const size=()=>Math.min(pool().length,5);
 const speakWord=w=>{if(!w||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(w);u.lang='en-GB';u.rate=.72;speechSynthesis.speak(u);};
 const shown=s=>typeof textCase==='function'?textCase(String(s)):String(s);
 const learning=(el,s)=>{el.textContent=shown(s);el.classList.toggle('cursive',String(mode||'').startsWith('cursive'));return el;};
 const completionHtml='<div class="game-fireworks">✨ 🎆 ✨ 🎉 ⭐</div><div class="game-dino">🦕</div><h1>Hooray!</h1><p>All tasks are complete!</p><button class="primary game-again">Play again</button>';
 const empty=(host,min)=>{host.innerHTML='<div class="game-header"><button class="game-back">← Games</button></div><div class="game-empty"><div class="game-dino">🦕</div><h2>More words needed</h2><p>Learn a few more sounds to unlock this game.</p><small>This game needs at least '+min+' decodable word'+(min===1?'':'s')+'.</small></div>';host.querySelector('.game-back').onclick=showList;};
 const style=document.createElement('style');style.textContent=`
 #gamesView{min-height:0;flex:1;width:100%;max-width:1120px;margin:0 auto;overflow:auto;padding:12px 0 24px;color:#123f73}
 .games-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:22px;width:min(100%,760px);margin:28px auto}
.game-card{min-height:150px;background:#f8fbff;color:#123f73;border:1px solid #cbd9ea;border-radius:22px;box-shadow:0 4px 12px #123f7315;font-size:22px;display:grid;place-items:center;gap:6px}.game-card span{font-size:48px}.game-card:active{background:#2389e8;color:#fff;transform:scale(.985)}
 .en-game{width:min(100%,920px);margin:0 auto;text-align:center;position:relative}.game-header{display:flex;align-items:center;justify-content:center;position:relative;min-height:58px}.game-back{position:absolute;left:0;background:#f8fbff;color:#123f73;border:1px solid #cbd9ea}.game-title{font-size:25px;font-weight:850}.game-progress{display:flex;justify-content:center;gap:7px;margin:16px auto 24px}.game-step{width:25px;height:25px;border-radius:50%;background:#edf4fb;border:1px solid #cbd9ea;font-size:15px;display:grid;place-items:center}.game-step.done{background:#35b96f;color:white;border-color:#35b96f}.game-task{min-height:330px;display:grid;align-content:center;justify-items:center;gap:24px;position:relative;padding:0 76px}.game-picture{background:transparent;font-size:64px;min-height:70px;padding:0}.game-prompt{font-size:25px;font-weight:800}.game-answers{display:flex;flex-wrap:wrap;justify-content:center;gap:14px}.game-answer,.build-tile,.build-slot{min-width:92px;min-height:70px;padding:10px 18px;background:#f8fbff;color:#123f73;border:1px solid #cbd9ea;box-shadow:0 4px 12px #123f7315;border-radius:16px;font-size:34px;font-weight:800}.game-answer.correct,.build-slot.correct{background:#35b96f;color:white;border-color:#35b96f}.game-answer.wrong{box-shadow:0 0 0 3px #d6e0eb inset}.game-nav{position:absolute;top:50%;transform:translateY(-50%);width:58px;height:58px;min-height:58px;padding:0;border-radius:50%;background:white;color:#123f73;border:1px solid #cbd9ea}.game-prev{left:5px}.game-next{right:5px}.game-next.ready{background:#35b96f;color:#fff;border-color:#35b96f}.game-complete,.game-empty{min-height:430px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:12px}.game-complete h1,.game-complete p,.game-empty h2,.game-empty p{margin:0}.game-dino{font-size:74px}.game-fireworks{font-size:34px}.game-again{margin-top:22px}.build-slots,.build-tiles{display:flex;flex-wrap:wrap;justify-content:center;gap:10px}.build-slot{min-width:66px}.build-slot.empty{background:transparent;box-shadow:none;border:0;border-bottom:4px solid #cbd9ea;border-radius:0}.build-tile{min-width:66px}.build-tile:disabled{visibility:hidden}.missing-pair{display:grid;grid-template-columns:1fr 1fr;gap:20px;width:min(100%,520px)}.missing-word{min-height:86px;padding:15px;border-radius:16px;background:#f8fbff;border:1px solid #cbd9ea;font-size:38px;font-weight:800;display:grid;place-items:center}.catch-area{position:relative;width:100%;height:330px;overflow:hidden}.catch-answer{position:absolute;min-width:130px;min-height:78px;transition:transform 5s ease-in-out}.catch-answer.correct{background:#35b96f;color:white}.game-empty small{color:#7d8599}
 @media(max-width:700px){#childView .tabs{width:min(78%,360px)}.games-grid{gap:12px;margin-top:12px}.game-card{min-height:112px;font-size:17px}.game-card span{font-size:38px}.game-task{padding:0 54px;min-height:290px}.game-answer,.build-tile,.build-slot{font-size:27px;min-width:68px;min-height:60px}.game-nav{width:48px;height:48px;min-height:48px}.game-back{font-size:14px;padding:8px 10px}.missing-word{font-size:30px}}
 /* Unified Games visual system: EN Reading workspace + current RU game design. */
 #childView:has(#gamesView:not([hidden])){height:100dvh;overflow:hidden;display:flex;flex-direction:column;padding:24px 44px 38px;background:#fffdf8;color:#123f73}
 #childView:has(#gamesView:not([hidden])) #gamesView{min-height:0;flex:1;width:100%;max-width:none;margin:0;overflow:hidden;padding:0}
 #childView:has(#gamesView:not([hidden])) #gameHost{width:100%;height:100%;min-height:0;flex:1}
 #childView:has(#gamesView:not([hidden])) .find-game,#childView:has(#gameHost:not([hidden])) .en-game{width:100%;max-width:none;height:100%;margin:0;display:flex;flex-direction:column;position:relative;text-align:center;overflow:visible}
 #childView:has(#gamesView:not([hidden])) .find-header,#childView:has(#gameHost:not([hidden])) .game-header{width:100%;margin:0;min-height:46px;display:flex;align-items:center;justify-content:space-between;flex:0 0 auto;position:relative}
 #childView:has(#gamesView:not([hidden])) .find-back,#childView:has(#gameHost:not([hidden])) .game-back{position:static;min-height:44px;padding:7px 4px;background:transparent;color:#55746d;border:0;border-radius:10px;font-size:16px;font-weight:700;box-shadow:none}
 #childView:has(#gamesView:not([hidden])) .find-title,#childView:has(#gameHost:not([hidden])) .game-title{position:absolute;left:50%;transform:translateX(-50%);color:#123f73;font-size:20px;font-weight:800}
 /* RU Find mode selector in the normal header/tab slot. */
 #childView .find-modes{position:fixed;z-index:12;top:34px;left:50%;transform:translateX(-50%);display:grid;grid-template-columns:repeat(2,minmax(0,1fr));width:min(100%,390px);margin:0;padding:4px;background:#edf4fb;border:1px solid #d5e1ef;border-radius:24px}
 #childView .find-mode{min-height:52px;border-radius:20px;padding:6px 14px;background:transparent;color:#123f73;font-size:16px;font-weight:750}
 #childView .find-mode.active{background:#2389e8;color:#fff;box-shadow:0 3px 10px #2389e83a}
 /* Native RU dinosaur track used by Find. */
 #childView .dino-track{position:relative;width:min(78%,600px);height:82px;margin:34px auto 5px;flex:0 0 82px;padding-left:46px!important;padding-right:46px!important;transform:translateY(16px)!important;overflow:visible!important}
 #childView .dino-path{position:absolute;left:36px;right:50px;top:48px;height:6px;background:#d9e1e8;border-radius:99px}
 #childView .dino-steps{position:absolute;left:39px;right:53px;top:35px;display:flex;justify-content:space-between}
 #childView .dino-step{width:31px;height:31px;border-radius:50%;background:#fff;border:4px solid #d5dde6;transition:.25s transform,.25s background}
 #childView .dino-step.done{background:#35b96f;border-color:#35b96f;transform:scale(1.06);color:#fff;display:flex;align-items:center;justify-content:center}
 #childView .dino-step.half{background:linear-gradient(90deg,#35b96f 50%,#fff 50%);border-color:#35b96f #d5dde6 #d5dde6 #35b96f}
 #childView .step-check{font-size:20px;font-weight:900;line-height:1;color:#fff}
 #childView .dino{position:absolute;left:0;top:-9px;font-size:68px;line-height:1;transition:left .42s cubic-bezier(.2,.8,.25,1);z-index:4!important;transform:translate(-10px,-22px) scaleX(-1)!important}
 #childView .dino-finish{position:absolute;right:10px;top:2px;font-size:44px;z-index:2;transform:translate(38px,-2px)!important}
 /* EN shell gets the same RU progress scale without changing its JS-generated DOM. */
 #childView #gameHost .game-progress{position:relative;width:min(78%,600px);height:82px;min-height:82px;margin:34px auto 5px;padding:35px 46px 0;display:flex;justify-content:space-between;gap:0;flex:0 0 82px;transform:translateY(16px);box-sizing:border-box}
 #childView #gameHost .game-progress:before{content:"";position:absolute;left:82px;right:96px;top:48px;height:6px;background:#d9e1e8;border-radius:99px}
 #childView #gameHost .game-progress:after{content:"🦕";position:absolute;left:0;top:-9px;font-size:68px;line-height:1;transform:translate(-10px,-22px) scaleX(-1);z-index:4}
 #childView #gameHost .game-step{position:relative;z-index:2;box-sizing:border-box;flex:0 0 31px;width:31px;height:31px;border-radius:50%;background:#fff;border:4px solid #d5dde6;color:#fff;font-size:20px;font-weight:900;line-height:1;display:flex;align-items:center;justify-content:center}
 #childView #gameHost .game-step.done{background:#35b96f;color:#fff;border-color:#35b96f;transform:scale(1.06)}
 #childView #gameHost .game-step:last-child:after{content:"🏁";position:absolute;left:calc(100% + 4px);top:-33px;font-size:44px;line-height:1;transform:translate(38px,-2px);z-index:3}
 /* Shared RU task/navigation geometry. */
 #childView .find-question-row,#childView #gameHost .game-task{position:relative;min-height:0;flex:1;width:100%;display:flex;align-items:center;justify-content:center;padding:8px 145px 28px;margin:0;box-sizing:border-box}
 #childView .find-nav-arrow,#childView #gameHost .game-nav{position:absolute;top:46%;transform:translateY(-50%);width:58px;height:58px;min-height:58px;padding:0;border:1.5px solid #d2deea;border-radius:50%;background:#fff;color:#123f73;box-shadow:0 2px 8px #123f730d;display:flex;align-items:center;justify-content:center;font-size:34px;line-height:1}
 #childView .find-nav-arrow:first-child,#childView #gameHost .game-prev{left:34px}
 #childView .find-nav-arrow:last-child,#childView #gameHost .game-next{right:34px}
 #childView .find-nav-arrow:disabled,#childView #gameHost .game-nav:disabled{opacity:.32;cursor:default}
 /* Find = current RU Find component design. */
 #childView .find-question{display:flex;align-items:center;justify-content:center;gap:16px;margin:0;color:#123f73;font-size:clamp(42px,6vw,68px);font-weight:800;line-height:1.05}
 #childView .find-picture,#childView #gameHost .game-picture{width:112px;height:112px;min-width:112px;min-height:112px;padding:6px;background:transparent;border:0;border-radius:20px;box-shadow:none;font-size:82px;line-height:1;display:flex;align-items:center;justify-content:center}
 #childView .find-answers{--find-cols:2;flex:0 0 auto;display:grid;grid-template-columns:repeat(var(--find-cols),minmax(0,1fr));gap:22px;width:min(100%,840px);margin:0 auto 2px}
 #childView .find-answers:has(.find-answer:nth-child(3)){--find-cols:3}
 #childView .find-answer{min-width:0;min-height:82px;padding:12px 18px;border-radius:17px;background:#f8fbff;color:#123f73;border:1px solid #cbd9ea;box-shadow:0 4px 12px #123f7315;font-size:clamp(30px,4.2vw,54px);font-weight:800;line-height:1.05;white-space:normal;overflow-wrap:anywhere;display:flex;align-items:center;justify-content:center}
 #childView .find-answer.correct{background:#35b96f;color:#fff;border-color:#35b96f}#childView .find-answer.try-again{background:#edf4fb;border-color:#cbd9ea}
 /* Catch = current RU Catch component design. */
 #childView #gameHost .game-task:has(.catch-area){flex-direction:column;gap:0;padding:0 76px}
 #childView #gameHost .game-task:has(.catch-area) .game-picture{min-width:76px;width:auto;height:76px;min-height:76px;padding:0;font-size:48px}
 #childView #gameHost .catch-area{position:relative;width:100%;max-width:920px;height:330px;min-height:220px;overflow:hidden}
 #childView #gameHost .catch-answer{position:absolute;left:0;top:0;box-sizing:border-box;width:max-content;min-width:132px;max-width:calc(100% - 28px);height:auto;min-height:82px;padding:10px 26px;white-space:nowrap;overflow:visible;border-radius:17px;font-size:clamp(30px,5vw,40px);line-height:1.15;font-weight:800;transition-property:transform;transition-timing-function:ease-in-out}
 #childView #gameHost .catch-answer.correct{background:#35b96f;color:#fff}
 #childView #gameHost .game-task:has(.build-slots),#childView #gameHost .game-task:has(.missing-pair){flex-direction:column;gap:24px}
  /* Build Word = current RU component proportions. */
 #childView #gameHost .build-slots,#childView #gameHost .build-tiles{display:flex;flex-wrap:wrap;justify-content:center;gap:10px;width:100%}
 #childView #gameHost .build-slot,#childView #gameHost .build-tile{width:clamp(50px,12vw,68px);height:clamp(58px,14vw,76px);min-height:0;padding:4px;border-radius:14px;font-size:clamp(28px,8vw,40px);font-weight:800}
 #childView #gameHost .build-slot{background:#f8fbff;color:#123f73;border:1px solid #cbd9ea;border-bottom:4px solid #cbd9ea}
 #childView #gameHost .build-slot.empty{background:transparent;border:0;border-bottom:4px solid #cbd9ea;border-radius:0;box-shadow:none}
 #childView #gameHost .build-slot.correct{background:#35b96f;color:#fff;border-color:#35b96f}
 #childView #gameHost .build-tile{background:#f8fbff;color:#123f73;border:1px solid #cbd9ea;box-shadow:0 4px 12px #123f7315}
 /* What's Missing = current RU component proportions. */
 #childView #gameHost .game-prompt{font-size:24px;font-weight:800;color:#123f73;min-height:30px}
 #childView #gameHost .missing-pair{display:grid;grid-template-columns:1fr 1fr;gap:24px;width:100%;align-items:center}
 #childView #gameHost .missing-word{display:flex;align-items:center;justify-content:center;min-height:86px;padding:12px;border-radius:16px;background:#f8fbff;border:1px solid #cbd9ea;color:#123f73;font-size:clamp(30px,8vw,46px);font-weight:800}
 #childView #gameHost .game-answers{display:grid;grid-template-columns:1fr 1fr;gap:14px;width:100%;min-height:70px}
 #childView #gameHost .game-answer{min-height:64px;border-radius:14px;background:#f8fbff;color:#123f73;border:1px solid #cbd9ea;box-shadow:0 4px 12px #123f7315;font-size:clamp(24px,6vw,34px);font-weight:800}
 #childView #gameHost .game-answer.correct{background:#35b96f;color:#fff;border-color:#35b96f}#childView #gameHost .game-answer.wrong{box-shadow:0 0 0 2px #cbd9ea inset}
 @media(max-width:700px){
  #childView:has(#gamesView:not([hidden])){padding:10px 14px 18px}
  #childView:has(#gamesView:not([hidden])) #gamesView{max-width:100%;overflow:auto}
  #childView .find-header,#childView #gameHost .game-header{min-height:42px}
  #childView .find-back,#childView #gameHost .game-back{font-size:15px;min-height:40px}
  #childView .find-title,#childView #gameHost .game-title{font-size:18px}
  #childView .find-modes{top:17px;width:min(58%,280px);padding:4px}
  #childView .find-mode{min-height:40px;border-radius:20px;padding:4px 8px;font-size:15px}
  #childView .dino-track{width:100%;height:70px;flex-basis:70px;padding-left:38px!important;padding-right:38px!important;transform:translateY(10px)!important;margin-top:28px}
  #childView .dino-path{left:29px;right:43px;top:42px;height:5px}#childView .dino-steps{left:31px;right:46px;top:31px}#childView .dino-step{width:26px;height:26px;border-width:3px}
  #childView .dino{font-size:58px;top:-7px;transform:translate(-8px,-19px) scaleX(-1)!important}
  #childView .dino-finish{right:3px;top:4px;font-size:37px;transform:translate(31px,-2px)!important}
  #childView #gameHost .game-progress{width:100%;height:70px;min-height:70px;flex-basis:70px;margin-top:28px;padding:31px 38px 0;transform:translateY(10px)}
  #childView #gameHost .game-progress:before{left:67px;right:81px;top:42px;height:5px}
  #childView #gameHost .game-progress:after{font-size:58px;top:-7px;transform:translate(-8px,-19px) scaleX(-1)}
  #childView #gameHost .game-step{flex-basis:26px;width:26px;height:26px;border-width:3px}
  #childView #gameHost .game-step:last-child:after{font-size:37px;top:-27px;transform:translate(31px,-2px)}
  #childView .find-question-row,#childView #gameHost .game-task{padding:2px 55px 12px}
  #childView .find-nav-arrow,#childView #gameHost .game-nav{width:48px;height:48px;min-height:48px;top:45%;font-size:29px}
  #childView .find-nav-arrow:first-child,#childView #gameHost .game-prev{left:0}#childView .find-nav-arrow:last-child,#childView #gameHost .game-next{right:0}
  #childView .find-question{gap:10px;font-size:clamp(34px,10vw,48px)}
  #childView .find-picture,#childView #gameHost .game-picture{width:82px;height:82px;min-width:82px;min-height:82px;font-size:62px;padding:2px}
  #childView .find-answers{gap:10px;width:min(100%,440px)}
  #childView .find-answer{min-height:68px;padding:9px 10px;border-radius:14px;font-size:clamp(28px,9vw,42px)}
  #childView #gameHost .game-task:has(.catch-area){padding:0 55px}
  #childView #gameHost .game-task:has(.catch-area) .game-picture{min-width:76px;width:auto;height:76px;min-height:76px;font-size:48px}
  #childView #gameHost .catch-answer{min-width:112px;max-width:calc(100% - 20px);min-height:70px;padding:8px 18px;font-size:clamp(28px,8vw,36px)}
  #childView #gameHost .build-slot,#childView #gameHost .build-tile{width:clamp(44px,13vw,58px);height:clamp(52px,15vw,66px);font-size:clamp(25px,8vw,34px)}
  #childView #gameHost .missing-pair{gap:10px}#childView #gameHost .missing-word{min-height:72px;padding:8px}
  #childView #gameHost .game-prompt{font-size:21px}#childView #gameHost .game-answer{min-height:58px}
 }
 @media(max-width:430px){#childView .find-answers:has(.find-answer:nth-child(3)){grid-template-columns:repeat(2,minmax(0,1fr))}#childView .find-answers:has(.find-answer:nth-child(3)) .find-answer:last-child{grid-column:1/-1}}
 @media(max-width:390px){#childView:has(#gamesView:not([hidden])){padding-left:10px;padding-right:10px}}
 @media(max-width:340px){#childView .find-answers{grid-template-columns:1fr!important}}

 `;document.head.appendChild(style);
 const gamesTab=$('gamesTab'),view=$('gamesView'),grid=$('gamesGrid'),host=$('gameHost');if(!gamesTab||!view||!grid||!host)return;let active=null;
 const hidePractice=()=>{['practice','finish'].forEach(id=>{const e=$(id);if(e)e.hidden=true;});};
 function showList(){active=null;hidePractice();view.hidden=false;$('findGame').hidden=true;grid.hidden=false;host.hidden=true;gamesTab.classList.add('on');$('soundsTab')?.classList.remove('on');$('wordsTab')?.classList.remove('on');}
 const leaveGames=()=>{view.hidden=true;gamesTab.classList.remove('on');active=null;};
 $('soundsTab')?.addEventListener('click',leaveGames);$('wordsTab')?.addEventListener('click',leaveGames);gamesTab.addEventListener('click',showList);
 const progressHtml=(tasks)=>'<div class="game-progress">'+tasks.map(t=>'<span class="game-step'+(t.rewarded?' done':'')+'">'+(t.rewarded?'✓':'')+'</span>').join('')+'</div>';
 const finish=(restart)=>{host.innerHTML='<div class="game-complete">'+completionHtml+'</div>';host.querySelector('.game-again').onclick=restart;};
 const taskEngine=(tasks,render,restart)=>{let original=tasks,session=[...tasks],i=0;const current=()=>session[i],done=()=>original.length&&original.every(t=>t.rewarded);const nav=()=>{const prev=host.querySelector('.game-prev'),next=host.querySelector('.game-next');if(prev)prev.disabled=i===0;if(next){next.disabled=!current()?.completed;next.classList.toggle('ready',!!current()?.completed);}};const redraw=()=>{render(current(),{original,session,index:i,current,redraw,nav,next,prev,reward});nav();};const reward=(t,correct)=>{t.attempted=true;if(!correct){t.hadWrongAttempt=true;return false;}t.completed=true;if(!t.hadWrongAttempt&&!t.rewarded)t.rewarded=true;return t.rewarded;};const retry=()=>{session=shuffle(original.filter(t=>!t.rewarded).map(t=>({...t,attempted:false,completed:false,hadWrongAttempt:false})));i=0;redraw();};function next(){if(!current()?.completed)return;if(i<session.length-1){i++;redraw();}else if(done())finish(restart);else retry();}function prev(){if(i>0){i--;redraw();}}redraw();};
 const shell=(title,body,steps)=>{host.hidden=false;grid.hidden=true;host.innerHTML='<div class="en-game"><div class="game-header"><button class="game-back">← Games</button><span class="game-title">'+title+'</span></div>'+progressHtml(steps)+'<div class="game-task"><button class="game-nav game-prev">‹</button>'+body+'<button class="game-nav game-next">›</button></div></div>';host.querySelector('.game-back').onclick=showList;};
 function startFind(){
 active='find';grid.hidden=true;host.hidden=true;const findGame=$('findGame'),soundsMode=$('findSoundsMode'),wordsMode=$('findWordsMode'),answers=$('findAnswers'),findPicture=$('findPicture'),findDinoSteps=$('findDinoSteps'),findDino=$('findDino'),findPrev=$('findPrev'),findNext=$('findNext');if(!findGame||!soundsMode||!wordsMode||!answers||!findPicture||!findDinoSteps||!findDino||!findPrev||!findNext)return;findGame.hidden=false;
 let findMode='sounds',findTaskIndex=0,wordSession=[],soundSession=[],wordOriginal=[],soundOriginal=[];
 const resetAttempt=t=>{t.attempted=false;t.completed=false;t.hadWrongAttempt=false;return t;},markWrong=t=>{if(!t.completed){t.attempted=true;t.hadWrongAttempt=true;}},markCorrect=t=>{if(t.completed)return false;t.attempted=true;t.completed=true;const rewarded=!t.hadWrongAttempt&&!t.rewarded;if(rewarded)t.rewarded=true;return rewarded;};
 const wordPool=()=>pool(),soundPool=()=>soundsThroughLevel().filter(soundMastered);
 const createWords=()=>{const p=wordPool();if(p.length<2){wordOriginal=[];wordSession=[];return;}const targets=shuffle(p).slice(0,Math.min(p.length,size()));wordOriginal=createDoubleExposureTasks(targets,p,(targetWord,distractor)=>({targetWord,answers:distractor?shuffle([targetWord,distractor]):[targetWord],attempted:false,completed:false,hadWrongAttempt:false,rewarded:false}));wordSession=[...wordOriginal];};
 const createSounds=()=>{const p=soundPool();if(p.length<2){soundOriginal=[];soundSession=[];return;}const targets=shuffle(p).slice(0,Math.min(p.length,size()));soundOriginal=createDoubleExposureTasks(targets,p,(targetSound,distractor)=>({targetSound,answers:distractor?shuffle([targetSound,distractor]):[targetSound],attempted:false,completed:false,hadWrongAttempt:false,rewarded:false}));soundSession=[...soundOriginal];};
 const session=()=>findMode==='words'?wordSession:soundSession,original=()=>findMode==='words'?wordOriginal:soundOriginal,goal=()=>original().length,current=()=>session()[findTaskIndex],progress=()=>original().filter(t=>t.rewarded).length;
 const updateProgress=()=>{const p=progress(),g=goal();[...findDinoSteps.children].forEach((step,i)=>{const done=i<p;step.classList.toggle('done',done);step.innerHTML=done?'<span class="step-check">✓</span>':'';});const pct=g?Math.min(100,p/g*100):0;findDino.style.left='calc('+pct+'% - '+(pct/100*46)+'px)';};
 const buildProgress=()=>{findDinoSteps.replaceChildren();for(let i=0;i<goal();i++){const step=document.createElement('span');step.className='dino-step';findDinoSteps.append(step);}updateProgress();};
 const refreshNav=()=>{findPrev.disabled=findTaskIndex===0;findNext.disabled=!current()?.completed;findNext.classList.toggle('game-nav-success',!!current()?.completed);};
 const celebrate=()=>{const burst=document.createElement('div');burst.className='correct-confetti';burst.setAttribute('aria-hidden','true');const bits=['🎉','✨','⭐','●','◆','★','●','✨','◆','★'];burst.innerHTML=bits.map((x,i)=>'<span style="--i:'+i+'">'+x+'</span>').join('');findGame.appendChild(burst);setTimeout(()=>burst.remove(),850);};
 const complete=()=>{findGame.hidden=true;host.hidden=false;host.innerHTML='<div class="game-complete"><div class="game-fireworks">✨ 🎆 ✨ 🎉 ⭐</div><div class="game-dino">🦕</div><h1>Hooray!</h1><p>All tasks completed!</p><button class="game-again">Again</button></div>';host.querySelector('.game-again').onclick=()=>{host.hidden=true;findGame.hidden=false;startSession();};};
 const allDone=()=>goal()>0&&progress()===goal(),remediation=()=>{const pending=original().filter(t=>!t.rewarded).map(resetAttempt);if(!pending.length){complete();return;}if(findMode==='words')wordSession=shuffle(pending);else soundSession=shuffle(pending);findTaskIndex=0;renderTask();},nextTask=()=>{if(!current()?.completed)return;if(findTaskIndex<session().length-1){findTaskIndex++;renderTask();}else if(allDone())complete();else remediation();};
 const renderTask=()=>{const t=current();if(!t){answers.innerHTML='<div class="game-empty"><h2>More '+(findMode==='words'?'words':'sounds')+' needed</h2></div>';findPicture.textContent='🔊';refreshNav();return;}const isWords=findMode==='words',target=isWords?t.targetWord:t.targetSound;findPicture.textContent='🔊';findPicture.setAttribute('aria-label','Listen to '+shown(target));answers.replaceChildren(...t.answers.map(label=>{const correct=label===target,b=document.createElement('button');b.type='button';b.className='find-answer'+(t.completed&&correct?' correct':'');learning(b,label);b.onclick=()=>{if(t.completed)return;if(correct){answers.querySelectorAll('.find-answer').forEach(x=>x.classList.remove('try-again'));b.classList.add('correct');const rewarded=markCorrect(t);if(rewarded){updateProgress();celebrate();}refreshNav();}else{markWrong(t);b.classList.add('try-again');refreshNav();}};return b;}));refreshNav();};
 const startSession=()=>{findMode==='words'?createWords():createSounds();findTaskIndex=0;buildProgress();renderTask();},setMode=m=>{findMode=m;soundsMode.classList.toggle('active',m==='sounds');wordsMode.classList.toggle('active',m==='words');startSession();};
 $('allGames').onclick=()=>{findGame.hidden=true;host.hidden=true;showList();};soundsMode.onclick=()=>setMode('sounds');wordsMode.onclick=()=>setMode('words');findPrev.onclick=()=>{if(findTaskIndex>0){findTaskIndex--;renderTask();}};findNext.onclick=nextTask;findPicture.onclick=()=>{const t=current();if(t)speakWord(findMode==='words'?t.targetWord:t.targetSound);};setMode(findMode);
}
function startCatch(){$('findGame').hidden=true;active='catch';const p=pool();if(p.length<2){host.hidden=false;grid.hidden=true;empty(host,2);return;}const words=shuffle(p).slice(0,size()),tasks=createDoubleExposureTasks(words,p,(targetWord,distractor)=>({targetWord,answers:shuffle([targetWord,distractor]),attempted:false,completed:false,hadWrongAttempt:false,rewarded:false}));taskEngine(tasks,(t,e)=>{shell('Catch','<button class="game-picture">'+(data(t.targetWord)?.picture||'🔊')+'</button><div class="catch-area"></div>',e.original);const area=host.querySelector('.catch-area');t.answers.forEach((label,j)=>{const b=document.createElement('button');b.className='game-answer catch-answer'+(t.completed&&label===t.targetWord?' correct':'');learning(b,label);b.style.transform='translate('+(j?65:5)+'%, '+(j?180:20)+'px)';b.onclick=()=>{if(t.completed)return;const ok=label===t.targetWord;e.reward(t,ok);if(ok){b.classList.add('correct');e.redraw();}else b.classList.add('wrong');};area.append(b);});if(!t.completed)setTimeout(()=>{[...area.children].forEach((b,j)=>b.style.transform='translate('+(j?5:65)+'%, '+(j?20:180)+'px)');},30);host.querySelector('.game-picture').onclick=()=>speakWord(t.targetWord);host.querySelector('.game-prev').onclick=e.prev;host.querySelector('.game-next').onclick=e.next;},startCatch);}
 const shuffledGraphemes=(gs,avoid='')=>{for(let n=0;n<12;n++){const x=shuffle(gs);if(x.join('|')!==avoid&&x.join('|')!==gs.join('|'))return x;}return [...gs].reverse();};
 function startBuild(){$('findGame').hidden=true;active='build';const p=pool();if(p.length<1){host.hidden=false;grid.hidden=true;empty(host,1);return;}const words=shuffle(p).slice(0,size()),tasks=[];words.forEach(targetWord=>{const gs=graphemes(targetWord),a=shuffledGraphemes(gs),b=shuffledGraphemes(gs,a.join('|'));[a,b].forEach(order=>tasks.push({targetWord,graphemes:gs,tiles:order.map((g,id)=>({id,g})),placed:Array(order.length).fill(null),attempted:false,completed:false,hadWrongAttempt:false,rewarded:false}));});const arranged=arrangeTasks(tasks);taskEngine(arranged,(t,e)=>{shell('Build Word','<button class="game-picture">'+(data(t.targetWord)?.picture||'🔊')+'</button><div class="build-slots"></div><div class="build-tiles"></div>',e.original);const slots=host.querySelector('.build-slots'),tiles=host.querySelector('.build-tiles');t.placed.forEach(tile=>{const b=document.createElement('button');b.className='build-slot'+(!tile?' empty':'')+(t.completed?' correct':'');if(tile)learning(b,tile.g);b.disabled=!tile||t.completed;if(tile)b.onclick=()=>{const k=t.placed.findIndex(x=>x?.id===tile.id);if(k>=0)t.placed[k]=null;e.redraw();};slots.append(b);});t.tiles.forEach(tile=>{const b=document.createElement('button');b.className='build-tile';learning(b,tile.g);b.disabled=t.completed||t.placed.some(x=>x?.id===tile.id);b.onclick=()=>{const k=t.placed.findIndex(x=>x===null);if(k<0)return;t.placed[k]=tile;if(t.placed.every(Boolean)){const assembled=t.placed.map(x=>x.g).join('');const expected=t.graphemes.join('');const ok=assembled===expected;e.reward(t,ok);if(!ok)setTimeout(()=>{t.placed=Array(t.tiles.length).fill(null);e.redraw();},350);else e.redraw();}else e.redraw();};tiles.append(b);});host.querySelector('.game-picture').onclick=()=>speakWord(t.targetWord);host.querySelector('.game-prev').onclick=e.prev;host.querySelector('.game-next').onclick=e.next;},startBuild);}
 function startMissing(){$('findGame').hidden=true;active='missing';const p=pool();if(p.length<2){host.hidden=false;grid.hidden=true;empty(host,2);return;}const words=shuffle(p).slice(0,size()),tasks=[];words.forEach(targetWord=>{for(let n=0;n<2;n++){const other=shuffle(words.filter(w=>w!==targetWord))[0]||shuffle(p.filter(w=>w!==targetWord))[0];if(!other)continue;const distractor=shuffle(p.filter(w=>w!==targetWord&&w!==other))[0]||other;const first=Math.random()<.5?targetWord:other,second=first===targetWord?other:targetWord;tasks.push({targetWord,first,second,missing:targetWord,answers:shuffle([...new Set([targetWord,distractor])]),phase:'memorize',attempted:false,completed:false,hadWrongAttempt:false,rewarded:false});}});const arranged=arrangeTasks(tasks);let timer=0;const restart=()=>{clearTimeout(timer);startMissing();};taskEngine(arranged,(t,e)=>{clearTimeout(timer);const answer=t.phase==='answer';shell("What’s Missing?",'<div class="game-prompt">'+(answer?'What’s missing?':'Remember')+'</div><div class="missing-pair"><div class="missing-word" id="mw1"></div><div class="missing-word" id="mw2"></div></div><div class="game-answers"></div>',e.original);const one=host.querySelector('#mw1'),two=host.querySelector('#mw2');if(answer&&!t.completed&&t.first===t.missing)one.textContent='?';else learning(one,t.first);if(answer&&!t.completed&&t.second===t.missing)two.textContent='?';else learning(two,t.second);if(answer){const box=host.querySelector('.game-answers');t.answers.forEach(label=>{const b=document.createElement('button');b.className='game-answer'+(t.completed&&label===t.missing?' correct':'');learning(b,label);b.onclick=()=>{if(t.completed)return;const ok=label===t.missing;e.reward(t,ok);if(ok)e.redraw();else b.classList.add('wrong');};box.append(b);});}else{const sec=Number(localStorage.getItem('phonika-en-missing-memory-seconds')||10);timer=setTimeout(()=>{t.phase='answer';e.redraw();},[5,7,10,15].includes(sec)?sec*1000:10000);}host.querySelector('.game-prev').onclick=e.prev;host.querySelector('.game-next').onclick=e.next;},restart);}
 grid.querySelector('[data-game="find"]').onclick=startFind;grid.querySelector('[data-game="catch"]').onclick=startCatch;grid.querySelector('[data-game="build"]').onclick=startBuild;grid.querySelector('[data-game="missing"]').onclick=startMissing;
 $('parentOpen')?.addEventListener('click',()=>{if(!view.hidden)localStorage.setItem('phonika-en-return-games',active||'list');});
 $('parentBack')?.addEventListener('click',()=>{const ret=localStorage.getItem('phonika-en-return-games');if(!ret)return;localStorage.removeItem('phonika-en-return-games');requestAnimationFrame(()=>{showList();if(ret==='find')startFind();else if(ret==='catch')startCatch();else if(ret==='build')startBuild();else if(ret==='missing')startMissing();});});
 window.PhonikaGamesEN={shuffle,arrangeTasks,availableWords,pool,graphemesForWord:graphemes};
}

if (document.readyState === 'loading') {
 document.addEventListener('DOMContentLoaded', initGames);
} else {
 initGames();
}
