'use strict';
const LEVELS=[
{title:'Short a — CVC word families',sounds:['s','a','t','p','n','c','b','h','m','f'],words:[['sat','🪑'],['pat','👋'],['tap','👆'],['nap','😴'],['pan','🍳'],['tan','🟤'],['ant','🐜'],['cat','🐱'],['bat','🦇'],['hat','🎩'],['mat','🧘'],['man','👨'],['fan','🪭'],['can','🥫'],['map','🗺️'],['cap','🧢'],['bag','👜'],['tag','🏷️'],['rag','🧽']]},
{title:'Short i — CVC word families',sounds:['i','l'],words:[['sit','🪑'],['hit','🎯'],['fit','💪'],['pit','🕳️'],['pin','📌'],['fin','🐟'],['tin','🥫'],['lip','👄'],['sip','🥤'],['tip','👉'],['pig','🐷']]},
{title:'Short o — CVC word families',sounds:['o','d','g'],words:[['hot','🔥'],['pot','🍲'],['dot','🔵'],['hop','🐰'],['top','🔝'],['dog','🐶'],['log','🪵'],['fog','🌫️'],['cot','🛏️']]},
{title:'Short e — CVC word families',sounds:['e','r'],words:[['pet','🐶'],['net','🥅'],['wet','💧'],['hen','🐔'],['pen','🖊️'],['ten','🔟'],['bed','🛏️'],['red','🔴'],['leg','🦵']]},
{title:'Short u — CVC word families',sounds:['u'],words:[['sun','☀️'],['run','🏃'],['fun','🎉'],['bug','🐛'],['hug','🤗'],['mug','☕'],['cup','🥤'],['pup','🐶'],['bus','🚌']]},
{title:'Mixed short vowels — true decoding',sounds:[],words:[['cat','🐱'],['pig','🐷'],['sun','☀️'],['bed','🛏️'],['dog','🐶'],['map','🗺️'],['red','🔴'],['sit','🪑'],['cup','🥤'],['hen','🐔'],['fox','🦊']]},
{title:'Digraphs — sh, ch, th, ck, ng',sounds:['sh','ch','th','ck','ng'],words:[['ship','🚢'],['shop','🏪'],['fish','🐟'],['chat','💬'],['chin','🙂'],['thin','📏'],['duck','🦆'],['sock','🧦'],['sing','🎵'],['ring','💍']]},
{title:'Consonant blends — st, sp, sw, fl, cl, tr, gr, fr',sounds:['st','sp','sw','fl','cl','tr','gr','fr'],words:[['stop','🛑'],['spin','🌀'],['swim','🏊'],['flag','🚩'],['clap','👏'],['trip','🧳'],['grin','😁'],['frog','🐸']]},
{title:'Magic e — long vowels',sounds:['a_e','i_e','o_e','u_e'],words:[['cake','🎂'],['lake','🏞️'],['make','🛠️'],['name','🏷️'],['bike','🚲'],['kite','🪁'],['five','5️⃣'],['home','🏠'],['hope','🤞'],['cube','🧊']]},
{title:'Vowel teams — ee, ai, ay, oa, oo',sounds:['ee','ai','ay','oa','oo'],words:[['see','👀'],['bee','🐝'],['feet','🦶'],['rain','🌧️'],['train','🚆'],['day','☀️'],['play','⚽'],['boat','⛵'],['goat','🐐'],['moon','🌙']]}
];
const ASSOC={s:['sun','☀️'],a:['apple','🍎'],t:['tiger','🐯'],p:['pig','🐷'],i:['insect','🐞'],n:['nest','🪺'],m:['map','🗺️'],d:['dog','🐶'],g:['goat','🐐'],o:['orange','🍊'],c:['cat','🐱'],k:['kite','🪁'],e:['egg','🥚'],u:['umbrella','☂️'],r:['rabbit','🐰'],h:['hat','🎩'],b:['ball','⚽'],f:['fish','🐟'],l:['lion','🦁'],j:['jam','🍓'],v:['van','🚐'],w:['web','🕸️'],x:['box','📦'],y:['yak','🐂'],z:['zebra','🦓'],ck:['duck','🦆'],ff:['puff','💨'],ll:['bell','🔔'],ss:['kiss','💋'],st:['stop','🛑'],sp:['spin','🌀'],sn:['snail','🐌'],cr:['crab','🦀'],tr:['tree','🌳'],pl:['plant','🌱'],bl:['block','🧱'],cl:['clap','👏'],fr:['frog','🐸'],gr:['grin','😁'],sh:['ship','🚢'],ch:['chair','🪑'],th:['thumb','👍'],ng:['ring','💍'],qu:['queen','👑'],'a_e':['cake','🎂'],'i_e':['bike','🚲'],'o_e':['home','🏠'],'u_e':['cube','🧊'],ai:['rain','🌧️'],ay:['play','⚽'],ee:['feet','🦶'],ea:['sea','🌊'],oa:['boat','⛵'],ow:['snow','❄️'],oo:['moon','🌙'],ar:['car','🚗'],or:['fork','🍴'],ur:['turn','↩️'],er:['fern','🌿'],ir:['bird','🐦'],ou:['cloud','☁️'],oi:['coin','🪙'],oy:['boy','👦'],igh:['night','🌙'],air:['chair','🪑'],ear:['hear','👂'],ure:['pure','💧']};
const VOWEL_GRAPHEMES=new Set(['a','e','i','o','u','a_e','i_e','o_e','u_e','ai','ay','ee','ea','oa','ow','oo','ar','or','ur','er','ir','ou','oi','oy','igh','air','ear','ure']);
const SIZE=5,GOAL=3,$=id=>document.getElementById(id);let level=Math.min(10,Math.max(1,Number(localStorage.getItem('phonika-level')||1))),section=localStorage.getItem('phonika-section')||'sounds',mode=localStorage.getItem('phonika-letter-mode')||'upper',soundProgress=JSON.parse(localStorage.getItem('phonika-en-sound-progress')||'{}'),wordProgress=JSON.parse(localStorage.getItem('phonika-en-word-progress')||'{}'),soundQueue=JSON.parse(localStorage.getItem('phonika-en-sound-queue')||'[]'),wordQueue=JSON.parse(localStorage.getItem('phonika-en-word-queue')||'[]'),index=0,marked=false,usedHint=false,sessionQueue=[],sessionIndex=0,sessionReads=new Map(),soundSessionQueue=[],soundSessionIndex=0,soundSessionReads=new Map(),SESSION_GOAL=2;
const old=JSON.parse(localStorage.getItem('phonika-letter-progress')||'{}');Object.entries(old).forEach(([k,v])=>{if(v>=GOAL&&!soundProgress[k])soundProgress[k]={self:GOAL,mastered:true,at:Date.now()}});
function state(obj,k){if(typeof obj[k]==='number')obj[k]={self:obj[k],mastered:obj[k]>=GOAL,at:0};return obj[k]||(obj[k]={self:0,mastered:false,at:0})}function save(){localStorage.setItem('phonika-level',level);localStorage.setItem('phonika-section',section);localStorage.setItem('phonika-letter-mode',mode);localStorage.setItem('phonika-en-sound-progress',JSON.stringify(soundProgress));localStorage.setItem('phonika-en-word-progress',JSON.stringify(wordProgress));localStorage.setItem('phonika-en-sound-queue',JSON.stringify(soundQueue));localStorage.setItem('phonika-en-word-queue',JSON.stringify(wordQueue))}function soundsThroughLevel(){return LEVELS.slice(0,level).flatMap(x=>x.sounds)}function wordsThroughLevel(){return LEVELS.slice(0,level).flatMap(x=>x.words.map(w=>({word:w[0],picture:w[1],tricky:!!w[2]})))}function soundMastered(s){return state(soundProgress,s).mastered}
function graphemes(word){const all=soundsThroughLevel(),known=[...all].sort((a,b)=>b.length-a.length).filter(x=>!x.includes('_'));let out=[],magicIndex=-1,magicKey=null;if(word.endsWith('e')&&word.length>=4){for(let i=0;i<word.length-1;i++){const key=word[i]+'_e';if(all.includes(key)){magicIndex=i;magicKey=key;break}}}for(let i=0;i<word.length;){if(i===magicIndex){out.push(magicKey);i++;continue}if(magicKey&&i===word.length-1&&word[i]==='e'){i++;continue}const g=known.find(x=>word.startsWith(x,i));out.push(g||word[i]);i+=(g||word[i]).length}return [...new Set(out)]}function wordAvailable(w){return graphemes(w.word).every(soundMastered)}
function rotate(queue,candidates,progress){queue=queue.filter(x=>candidates.includes(x));const mastered=queue.filter(x=>state(progress,x).mastered);if(queue.length&&mastered.length>=4){mastered.sort((a,b)=>(state(progress,a).at||0)-(state(progress,b).at||0));queue=queue.filter(x=>x!==mastered[0])}for(const x of candidates)if(queue.length<SIZE&&!queue.includes(x)&&!state(progress,x).mastered)queue.push(x);for(const x of candidates)if(queue.length<SIZE&&!queue.includes(x))queue.push(x);return queue.slice(0,SIZE)}function shuffled(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a}
function wordFitsSounds(w,allowed){return graphemes(w.word).every(g=>allowed.has(g))}
function chooseWordSession(){refreshQueues();const pool=wordsThroughLevel().filter(wordAvailable).map(w=>w.word),previous=new Set(wordQueue.filter(w=>pool.includes(w)));let q=shuffled(pool.filter(w=>!previous.has(w))).concat(shuffled(pool.filter(w=>previous.has(w)))).slice(0,SIZE);wordQueue=q;save();return q}
function refreshQueues(){soundQueue=rotate(soundQueue,soundsThroughLevel(),soundProgress);save()}
function textCase(s){if(s.includes('_'))s=s.replace('_','');if(mode==='upper'||mode==='cursiveUpper')return s.toUpperCase();if(mode==='title'||mode==='cursiveTitle')return s[0].toUpperCase()+s.slice(1);return s.toLowerCase()}function color(el,text,isSound=false){el.replaceChildren();const shown=textCase(text);if(isSound){const span=document.createElement('span');span.textContent=shown;span.className=VOWEL_GRAPHEMES.has(text)?'vowel':'consonant';el.append(span);return}[...shown].forEach(ch=>{const span=document.createElement('span');span.textContent=ch;span.className='aeiou'.includes(ch.toLowerCase())?'vowel':'consonant';el.append(span)})}function currentKey(){refreshQueues();const q=section==='sounds'?(soundSessionQueue.length?soundSessionQueue:soundQueue):(sessionQueue.length?sessionQueue:wordQueue);const i=section==='sounds'?(soundSessionQueue.length?soundSessionIndex:index):sessionIndex;return q[i%Math.max(1,q.length)]}function currentWordObj(){return wordsThroughLevel().find(x=>x.word===currentKey())}
function render(){refreshQueues();const isSounds=section==='sounds',key=currentKey();$('finish').hidden=true;$('practice').hidden=false;$('soundCard').hidden=!isSounds;$('wordCard').hidden=isSounds;$('soundsTab').classList.toggle('on',isSounds);$('wordsTab').classList.toggle('on',!isSounds);$('help').hidden=false;marked=false;usedHint=false;$('mastery').disabled=false;$('mastery').classList.remove('done');$('mastery').textContent=isSounds?'✓ I know this sound':'✓ I read it myself';$('confirmation').textContent='';$('picture').hidden=true;$('showPicture').textContent='Show picture';if(!key){$('soundCard').textContent='';$('wordCard').textContent='';$('mastery').disabled=true;return}if(isSounds){color($('soundCard'),key,true);$('soundCard').classList.toggle('cursive',mode.startsWith('cursive'));$('picture').textContent=(ASSOC[key]||['','🔤'])[1]}else{color($('wordCard'),key);$('wordCard').classList.toggle('cursive',mode.startsWith('cursive'));$('picture').textContent=(currentWordObj()||{}).picture||'⭐'}save()}
function speak(){const isSounds=section==='sounds',key=currentKey();if(!key||!('speechSynthesis'in window))return;const text=isSounds?(ASSOC[key]||[key])[0]:(currentWordObj()||{}).word||key;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.rate=.72;speechSynthesis.speak(u)}function showPicture(){usedHint=true;$('picture').hidden=!$('picture').hidden;$('showPicture').textContent=$('picture').hidden?'Show picture':'Hide picture';if(!$('picture').hidden)speak();if(section==='words')$('mastery').disabled=true}function mark(){if(marked||usedHint)return;const key=currentKey(),obj=section==='sounds'?soundProgress:wordProgress,st=state(obj,key);st.self=Math.min(GOAL,st.self+1);if(st.self>=GOAL&&!st.mastered){st.mastered=true;st.at=Date.now()}marked=true;$('mastery').disabled=true;$('mastery').classList.add('done');$('mastery').textContent='✓ Counted';$('confirmation').textContent=st.mastered?'Mastered!':st.self+' / '+GOAL;refreshQueues();save()}function startWordSession(){sessionQueue=chooseWordSession();sessionIndex=0;sessionReads=new Map(sessionQueue.map(w=>[w,0]));render()}function startSoundSession(){refreshQueues();soundSessionQueue=[...soundQueue];soundSessionIndex=0;soundSessionReads=new Map(soundSessionQueue.map(s=>[s,0]));index=0;render()}
function next(){if(section==='sounds'){if(!soundSessionQueue.length)startSoundSession();const key=currentKey();if(key&&marked)soundSessionReads.set(key,Math.min(SESSION_GOAL,(soundSessionReads.get(key)||0)+1));const pending=soundSessionQueue.filter(s=>(soundSessionReads.get(s)||0)<SESSION_GOAL);if(!pending.length){soundSessionQueue=[];soundSessionIndex=0;$('practice').hidden=true;$('finish').hidden=false;return}soundSessionQueue=pending;soundSessionIndex=Math.min(soundSessionIndex+1,pending.length-1);index=soundSessionIndex;render();return}if(!sessionQueue.length)return;const key=currentKey();if(key&&marked)sessionReads.set(key,Math.min(SESSION_GOAL,(sessionReads.get(key)||0)+1));const oldQueue=[...sessionQueue],oldIndex=sessionIndex;const pending=oldQueue.filter(w=>(sessionReads.get(w)||0)<SESSION_GOAL);if(!pending.length){sessionQueue=[];sessionIndex=0;$('practice').hidden=true;$('finish').hidden=false;return}sessionQueue=pending;const oldNext=oldQueue[(oldIndex+1)%oldQueue.length];const nextPos=pending.indexOf(oldNext);sessionIndex=nextPos>=0?nextPos:Math.min(oldIndex,pending.length-1);render()}
function row(name,st){const d=document.createElement('div');d.className='row';const a=document.createElement('span');a.textContent=name;const b=document.createElement('span');b.className='status';b.textContent=st.mastered?'Mastered':st.self+' / '+GOAL;d.append(a,b);return d}function parentRender(){refreshQueues();$('levelButtons').replaceChildren(...LEVELS.map((x,i)=>{const b=document.createElement('button');b.className='level-choice'+(level===i+1?' selected':'');b.textContent=i+1;b.onclick=()=>{level=i+1;soundQueue=[];wordQueue=[];sessionQueue=[];index=0;refreshQueues();parentRender()};return b}));$('levelHint').textContent='Level '+level+' — '+LEVELS[level-1].title+'.';$('knownSounds').replaceChildren(...soundsThroughLevel().map(s=>{const b=document.createElement('button');b.className='known-sound '+(VOWEL_GRAPHEMES.has(s)?'vowel':'consonant')+(soundMastered(s)?' selected':'');b.textContent=textCase(s);b.onclick=()=>{const st=state(soundProgress,s);if(st.mastered)soundProgress[s]={self:0,mastered:false,at:0};else soundProgress[s]={self:GOAL,mastered:true,at:Date.now()};soundQueue=[];wordQueue=[];sessionQueue=[];refreshQueues();parentRender()};return b}));$('soundQueue').replaceChildren(...soundQueue.map(s=>row(textCase(s),state(soundProgress,s))));const ms=soundsThroughLevel().filter(soundMastered);$('masteredSounds').replaceChildren(...(ms.length?ms.map(s=>row(textCase(s),state(soundProgress,s))):[empty()]));$('wordQueue').replaceChildren(...wordQueue.map(w=>row(textCase(w),state(wordProgress,w))));const mw=wordsThroughLevel().map(x=>x.word).filter(w=>state(wordProgress,w).mastered);$('masteredWords').replaceChildren(...(mw.length?mw.map(w=>row(textCase(w),state(wordProgress,w))):[empty()]));$('mode').value=mode}function empty(){const p=document.createElement('p');p.className='empty';p.textContent='Nothing here yet.';return p}
$('showPicture').onclick=showPicture;$('help').onclick=()=>{usedHint=true;$('mastery').disabled=true;speak()};$('soundCard').onclick=()=>{if(section==='sounds')speak()};$('picture').onclick=null;$('mastery').onclick=mark;$('next').onclick=next;$('continue').onclick=()=>{section==='words'?startWordSession():startSoundSession()};$('soundsTab').onclick=()=>{section='sounds';startSoundSession()};$('wordsTab').onclick=()=>{section='words';index=0;startWordSession()};$('parentOpen').onclick=()=>{$('childView').hidden=true;$('parentView').hidden=false;document.body.style.overflow='auto';parentRender()};$('parentBack').onclick=()=>{$('parentView').hidden=true;$('childView').hidden=false;document.body.style.overflow='';render()};$('mode').onchange=e=>{mode=e.target.value;save();parentRender()};refreshQueues();if(section==='words')startWordSession();else startSoundSession();